FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Motoglobe POI search

Polls is a simple API allowing consumers to view polls and vote in them.

## POI [/poi{?page,category,center,radius}]

### Get POIs [GET]
+ Headers

        Accept-language: `hu,en-US;q=0.8,en;q=0.6`

+ Parameters
    + page (optional, number, `1`)
    + category (optional, array, [`1`])
    + center (required, string, `47.530907,19.039727`)
    
        GPS koordináták
        
    + radius (required, number, `5.67`)
    
        Kilométerben
    

+ Response 200 (application/json)

    + Attributes (array[POI,POI,POI,POI,POI,POI,POI,POI,POI,POI])

### Upload POI [POST]

+ Request (application/json)

    + Body

            {
                "name": "Motor bolt",
                "location": POILocation,
                "category_id": 3,
                "owner": false,
            }

+ Response 201 (application/json)

    + Body

            {
                "id": 1
            }

## POI Categories [/poi_category]

### Get POI categories [GET]

+ Headers

        Accept-language: hu,en-US;q=0.8,en;q=0.6

+ Response 200 (application/json)

    + Attributes (array[POICategory,POICategory,POICategory,POICategory,POICategory,POICategory,POICategory,POICategory,POICategory,POICategory,POICategory,POICategory,POICategory,POICategory,POICategory])

# Data structures

## POI (object)

+ id: 1 (number)
+ name: `Motor bolt` (string)
+ location
    + Include POILocation
+ category
    + Include POICategory
+ has_owner: false (boolean) //a hely tulajdonosa felvette-e már a kapcsolatot a motoglobe-bal
+ description: `Ez egy nagyon jo bolt. Van itt minden.` (optional, string)
+ website: `http://motorbolt.hu` (optional, string)
+ phone_number: `+3612345678` (optional, string)
+ opening_hours
    + Include POIOpening
+ published: false (boolean) //a motoglobe elfogadta-e már ezt a helyet (létrehozni az appból csak false-szal lehet majd!)

## POILocation (object)

+ display_address: `Budapest, Lajos u. 74., 1036` (string) 
    
    displayaddress google-ből (szabadszavas címet ide ne írjunk)
    
+ lat: 47.530907 (number)
+ lng: 19.039727 (number)

## POICategory (object)

+ id: 3 (number)
+ name: `Motor uzlet` (string)

## POIOpening (object)

+ periods: POIOpeningPeriod,POIOpeningPeriod,POIOpeningPeriod,POIOpeningPeriod,POIOpeningPeriod,POIOpeningPeriod,POIOpeningPeriod (array[POIOpeningPeriod])
    // is an array of opening periods covering seven days, starting from Sunday, in chronological order. 
+ weekday_text: `["Monday: 11:30 AM – 11:00 PM",
                  "Tuesday: 11:30 AM – 11:00 PM",
                  "Wednesday: 11:30 AM – 11:00 PM",
                  "Thursday: 11:30 AM – 11:00 PM",
                  "Friday: 11:30 AM – 11:00 PM",
                  "Saturday: 5:00 – 11:00 PM",
                  "Sunday: 11:30 AM – 11:00 PM"]` (array[string])
    // is an array of seven strings representing the formatted opening hours for each day of the week. If a language parameter was specified in the Place Details request,
    // the Places Service will format and localize the opening hours appropriately for that language. The ordering of the elements in this array depends on the language parameter.
    // Some languages start the week on Monday while others start on Sunday.

## POIOpeningPeriod (object)

+ open
    + Include POIOpeningDayTime
    // contains a pair of day and time objects describing when the place opens
+ close
    + Include POIOpeningDayTime
    // may contain a pair of day and time objects describing when the place closes. Note: If a place is always open, the close section will be missing from the response.
    // Applications can rely on always-open being represented as an open period containing day with value 0 and time with value 0000, and no close

## POIOpeningDayTime (object)

+ day: 1 (number)
    // a number from 0–6, corresponding to the days of the week, starting on Sunday. For example, 2 means Tuesday.
+ time: `1545` (string)
    // may contain a time of day in 24-hour hhmm format (values are in the range 0000–2359). The time will be reported in the place’s timezone.